import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { CookiesProvider } from 'next-client-cookies/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mega City Cab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      
      <body
    
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {/* <div className=" relative z-40"><NavBar /></div> */}
       <div className=" relative z- 0">
        <CookiesProvider>
          <NavBar />
          {children}
        </CookiesProvider>
       </div>
      </body>
    </html>
  );
}
